# Generated by Django 3.0.1 on 2020-01-05 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('verification_code', models.IntegerField(default=0)),
                ('code_expiry_date', models.DateTimeField(null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('security_question', models.CharField(max_length=100, null=True)),
                ('security_answer', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
